(function () {
  const TD = (window.TD = window.TD || {});

  TD.AssetManifest = {
    images: {
      forest_background: { src: "./assets/images/scenes/forest/background.png", width: 1280, height: 720, label: "Forest scene background" },
      forest_route: { src: "./assets/images/scenes/forest/route.png", width: 1280, height: 720, label: "Forest path overlay" },
      forest_props: { src: "./assets/images/scenes/forest/props.png", width: 1280, height: 720, label: "Forest decorations overlay" },
      forest_spawn: { src: "./assets/images/scenes/forest/spawn.png", width: 160, height: 180, label: "Forest enemy spawn art" },
      forest_base: { src: "./assets/images/scenes/forest/base.png", width: 180, height: 180, label: "Forest base art" },
      forest_slot_empty: { src: "./assets/images/scenes/forest/slot_empty.png", width: 48, height: 48, label: "Forest empty placement marker" },
      forest_soldier: { src: "./assets/images/scenes/forest/units/soldier.png", width: 72, height: 72, label: "Forest infantry sprite" },
      forest_archer: { src: "./assets/images/scenes/forest/units/archer.png", width: 72, height: 72, label: "Forest archer sprite" },
      forest_tower: { src: "./assets/images/scenes/forest/units/tower.png", width: 96, height: 120, label: "Forest tower sprite" },
      forest_monkey: { src: "./assets/images/scenes/forest/enemies/monkey.png", width: 72, height: 72, label: "Forest monkey enemy sprite" },
      forest_boar: { src: "./assets/images/scenes/forest/enemies/boar.png", width: 92, height: 72, label: "Forest boar enemy sprite" },
      forest_bear: { src: "./assets/images/scenes/forest/enemies/bear.png", width: 108, height: 92, label: "Forest bear enemy sprite" },
      forest_gorilla: { src: "./assets/images/scenes/forest/enemies/gorilla.png", width: 132, height: 118, label: "Forest gorilla enemy sprite" },
      forest_bat: { src: "./assets/images/scenes/forest/enemies/bat.png", width: 84, height: 58, label: "Forest bat enemy sprite" },
      beach_background: { src: "./assets/images/scenes/beach/background.png", width: 1280, height: 720, label: "Beach scene background" },
      beach_route: { src: "./assets/images/scenes/beach/route.png", width: 1280, height: 720, label: "Beach path overlay" },
      beach_props: { src: "./assets/images/scenes/beach/props.png", width: 1280, height: 720, label: "Beach decorations overlay" },
      beach_spawn: { src: "./assets/images/scenes/beach/spawn.png", width: 160, height: 180, label: "Beach enemy spawn art" },
      beach_base: { src: "./assets/images/scenes/beach/base.png", width: 234, height: 312, label: "Beach base art" },
      beach_slot_empty: { src: "./assets/images/scenes/beach/slot_empty.png", width: 48, height: 48, label: "Beach empty placement marker" },
      beach_soldier: { src: "./assets/images/scenes/beach/units/soldier.png", width: 72, height: 72, label: "Beach infantry sprite" },
      beach_soldier_idle_sheet: { src: "./assets/images/scenes/beach/units/soldier_idle.png", width: 1520, height: 2056, label: "Beach infantry idle spritesheet" },
      beach_soldier_attack_sheet: { src: "./assets/images/scenes/beach/units/soldier_attack.png", width: 1760, height: 1920, label: "Beach infantry attack spritesheet" },
      beach_archer: { src: "./assets/images/scenes/beach/units/archer.png", width: 72, height: 72, label: "Beach archer sprite" },
      beach_tower: { src: "./assets/images/scenes/beach/units/tower.png", width: 128, height: 181, label: "Beach tower sprite" },
      beach_hermit: { src: "./assets/images/scenes/beach/enemies/hermit.png", width: 35, height: 28, label: "Beach hermit crab enemy sprite" },
      beach_crab: { src: "./assets/images/scenes/beach/enemies/crab.png", width: 53, height: 42, label: "Beach crab enemy sprite" },
      beach_blackcat: { src: "./assets/images/scenes/beach/enemies/blackcat.png", width: 70, height: 56, label: "Beach black cat enemy sprite" },
      beach_gull: { src: "./assets/images/scenes/beach/enemies/gull.png", width: 88, height: 70, label: "Beach seagull enemy sprite" },
      beach_octopus: { src: "./assets/images/scenes/beach/enemies/octopus.png", width: 88, height: 70, label: "Beach octopus enemy sprite" },
      beach_seal: { src: "./assets/images/scenes/beach/enemies/seal.png", width: 105, height: 84, label: "Beach seal enemy sprite" },
      slot_empty: { src: "./assets/images/slot_empty.png", width: 48, height: 48, label: "Empty placement marker" },
      slot_filled: { src: "./assets/images/slot_filled.png", width: 48, height: 48, label: "Occupied placement marker" },
      soldier: { src: "./assets/images/soldier.png", width: 72, height: 72, label: "Infantry unit sprite" },
      archer: { src: "./assets/images/archer.png", width: 72, height: 72, label: "Archer unit sprite" },
      tower: { src: "./assets/images/tower.png", width: 96, height: 120, label: "Tower building sprite" },
      monkey: { src: "./assets/images/monkey.png", width: 72, height: 72, label: "Monkey enemy sprite" },
      boar: { src: "./assets/images/boar.png", width: 92, height: 72, label: "Boar enemy sprite" },
      bear: { src: "./assets/images/bear.png", width: 108, height: 92, label: "Bear enemy sprite" },
      gorilla: { src: "./assets/images/gorilla.png", width: 132, height: 118, label: "Gorilla enemy sprite" },
      bat: { src: "./assets/images/bat.png", width: 84, height: 58, label: "Bat enemy sprite" },
      hermit: { src: "./assets/images/hermit.png", width: 35, height: 28, label: "Hermit crab enemy sprite" },
      crab: { src: "./assets/images/crab.png", width: 53, height: 42, label: "Crab enemy sprite" },
      blackcat: { src: "./assets/images/blackcat.png", width: 70, height: 56, label: "Black cat enemy sprite" },
      gull: { src: "./assets/images/gull.png", width: 88, height: 70, label: "Seagull enemy sprite" },
      octopus: { src: "./assets/images/octopus.png", width: 175, height: 140, label: "Octopus enemy sprite" },
      seal: { src: "./assets/images/seal.png", width: 105, height: 84, label: "Seal enemy sprite" },
      stone: { src: "./assets/images/stone.png", width: 20, height: 20, label: "Stone projectile" },
      arrow: { src: "./assets/images/arrow.png", width: 28, height: 10, label: "Arrow projectile" },
      shell: { src: "./assets/images/shell.png", width: 26, height: 26, label: "Cannon shell projectile" },
      hud_gold: { src: "./assets/images/ui/hud_gold.png", width: 32, height: 32, label: "HUD gold icon" },
      hud_life: { src: "./assets/images/ui/hud_life.png", width: 32, height: 32, label: "HUD life icon" },
      hud_wave: { src: "./assets/images/ui/hud_wave.png", width: 32, height: 32, label: "HUD wave icon" },
      forest_button_soldier: { src: "./assets/images/scenes/forest/ui/button_soldier.png", width: 64, height: 64, label: "Forest soldier button icon" },
      forest_button_archer: { src: "./assets/images/scenes/forest/ui/button_archer.png", width: 64, height: 64, label: "Forest archer button icon" },
      forest_button_tower: { src: "./assets/images/scenes/forest/ui/button_tower.png", width: 64, height: 64, label: "Forest tower button icon" },
      beach_button_soldier: { src: "./assets/images/scenes/beach/ui/button_soldier.png", width: 64, height: 64, label: "Beach soldier button icon" },
      beach_button_archer: { src: "./assets/images/scenes/beach/ui/button_archer.png", width: 64, height: 64, label: "Beach archer button icon" },
      beach_button_tower: { src: "./assets/images/scenes/beach/ui/button_tower.png", width: 64, height: 64, label: "Beach tower button icon" },
      button_soldier: { src: "./assets/images/ui/button_soldier.png", width: 64, height: 64, label: "Soldier button icon" },
      button_archer: { src: "./assets/images/ui/button_archer.png", width: 64, height: 64, label: "Archer button icon" },
      button_tower: { src: "./assets/images/ui/button_tower.png", width: 64, height: 64, label: "Tower button icon" },
      panel_victory: { src: "./assets/images/ui/panel_victory.png", width: 520, height: 320, label: "Victory panel background" },
      panel_defeat: { src: "./assets/images/ui/panel_defeat.png", width: 520, height: 320, label: "Defeat panel background" }
    },
    audio: {
      worldmap_bgm: { src: "./assets/audio/worldmap/bgm.mp3", alt: "./assets/audio/worldmap/bgm.wav", label: "World map background music" },
      forest_bgm: { src: "./assets/audio/scenes/forest/bgm.mp3", alt: "./assets/audio/scenes/forest/bgm.wav", label: "Forest background music" },
      beach_bgm: { src: "./assets/audio/scenes/beach/bgm.mp3", alt: "./assets/audio/scenes/beach/bgm.wav", label: "Beach background music" },
      mystery_bgm: { src: "./assets/audio/scenes/mystery/bgm.mp3", alt: "./assets/audio/scenes/mystery/bgm.wav", label: "Mystery background music" },
      summit_bgm: { src: "./assets/audio/scenes/summit/bgm.mp3", alt: "./assets/audio/scenes/summit/bgm.wav", label: "Summit background music" },
      bgm: { src: "./assets/audio/bgm.mp3", alt: "./assets/audio/bgm.ogg", label: "Background music loop" },
      throw: { src: "./assets/audio/throw.wav", label: "Stone throw SFX" },
      arrow: { src: "./assets/audio/arrow.wav", label: "Arrow shot SFX" },
      cannon: { src: "./assets/audio/cannon.wav", label: "Cannon shot SFX" },
      hit: { src: "./assets/audio/hit.wav", label: "Hit SFX" },
      base_hurt: { src: "./assets/audio/base_hurt.wav", label: "Base hurt SFX" },
      enemy_die: { src: "./assets/audio/enemy_die.wav", label: "Enemy death SFX" },
      place: { src: "./assets/audio/place.wav", label: "Place unit SFX" },
      wave_start: { src: "./assets/audio/wave_start.wav", label: "Wave start SFX" },
      victory: { src: "./assets/audio/victory.wav", label: "Victory SFX" },
      celebrate: { src: "./assets/audio/celebrate.wav", label: "Celebration SFX" },
      defeat: { src: "./assets/audio/defeat.wav", label: "Defeat SFX" }
    }
  };
})();





